# Generated by Django 3.2.7 on 2021-10-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration',
            new_name='RegisterForm',
        ),
    ]
