# Generated by Django 3.2.7 on 2021-11-12 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resume', '0002_rename_registration_registerform'),
    ]

    operations = [
        migrations.CreateModel(
            name='createResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('address', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=122)),
                ('aboutyou', models.TextField(max_length=1000)),
                ('careerobj', models.TextField(max_length=500)),
                ('ssc', models.CharField(max_length=10)),
                ('hsc', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=10)),
                ('comname3', models.CharField(blank=True, max_length=500)),
                ('j3sd', models.DateField(blank=True, null=True)),
                ('j3ed', models.DateField(blank=True, null=True)),
                ('positiondet3', models.TextField(max_length=500)),
                ('comname2', models.CharField(blank=True, max_length=500)),
                ('j2sd', models.DateField(blank=True, null=True)),
                ('j2ed', models.DateField(blank=True, null=True)),
                ('positiondet2', models.TextField(max_length=500)),
                ('comname1', models.CharField(blank=True, max_length=500)),
                ('j1sd', models.DateField(blank=True, null=True)),
                ('j1ed', models.DateField(blank=True, null=True)),
                ('positiondet1', models.TextField(max_length=500)),
                ('references', models.TextField(max_length=600)),
                ('template', models.CharField(max_length=122)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
