# Generated by Django 3.2.7 on 2021-11-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_auto_20211113_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('query', models.TextField(max_length=1000)),
            ],
        ),
    ]
