# Generated by Django 3.2.7 on 2021-11-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fullname',
            new_name='fname',
        ),
    ]
